// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWnmk5h8aOk6mYrLyJq60EH-lp6DpWDU',
    appId: '1:243411160774:android:c2acac3cdaa8f9d3b291c7',
    messagingSenderId: '243411160774',
    projectId: 'flutternote-10028',
    storageBucket: 'flutternote-10028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmz-I8XnEWdsgNQoLqTn8OuGppwnfUUqU',
    appId: '1:243411160774:ios:31d48f21e8730bb8b291c7',
    messagingSenderId: '243411160774',
    projectId: 'flutternote-10028',
    storageBucket: 'flutternote-10028.appspot.com',
    iosClientId: '243411160774-287ugc5vd2va5te7vt66p2mjc1n387k4.apps.googleusercontent.com',
    iosBundleId: '234568',
  );
}
